const productos = [
    {
        id: 1,
        nombre: "BLACK MOUTH CUR",
        desc: "También conocido como southern cur, southern black mouth cur o yellow black mouth cur, es una raza de perro procedente del sudeste de los Estados Unidos.cada vez es más frecuente encontrarlo formando parte de la familia, pues su carácter sociable y leal lo convierte en un excelente perro de compañía.",
        origen:"Estados Unidos",
        precio: 100000,
        img:'src/https://t1.ea.ltmcdn.com/es/razas/5/8/8/black-mouth-cur_885_0_300_150.jpg',
        Stock: 3,
    },
    {
        id: 2,
        nombre: "PERRO MAJORELO O BARDINO",
        desc: "El perro majorero es la raza canina autóctona de la isla de Fuerteventura, en el archipiélago canario, donde se le conoce popularmente como perro bardino. Se trata de una raza que ha sido empleada durante más de seis siglos como perro guardián y perro pastor.",
        origen:"España",
        precio: 120000,
        img: 'src/https://t1.ea.ltmcdn.com/es/razas/0/9/8/perro-majorero-o-bardino_890_0_300_150.jpg',
        Stock: 5,   
    },
    {
        id: 3,
        nombre: "PASTOR IRLANDES",
        desc: "El pastor islandés en la raza canina autóctona de Islandia, lugar donde se considera un símbolo nacional muy querido. Debido a su resistencia, su agilidad e inteligencia, se ha empleado a lo largo de la historia para pastorear el ganado bovino y ovino. Sin embargo, también se considera un excelente perro de carácter alegre y amistoso.",
        origen:"Islandia",
        precio: 150000,
        img: 'src/https://t1.ea.ltmcdn.com/es/razas/2/9/8/pastor-islandes_892_0_600.jpg',
        Stock: 8, 
    },
    {
        id: 4,
        nombre: "NORTHEREN INUIT",
        desc: "El Northern inuit es una raza originaria de Gran Bretaña que se crio con la finalidad de obtener un perro con apariencia de lobo pero con el carácter propio de los perros domésticos. Pese a no ser una raza oficialmente reconocida, su popularidad es cada vez mayor, lo cual se debe en gran medida a su aparición en la famosa serie “Juego de Tronos”.",
        origen:"Reino Unidos",
        precio: 190000,
        img: 'src/https://t2.ea.ltmcdn.com/es/razas/6/8/5/northern-inuit_586_0_600.jpg',
        Stock: 7,    
    },
    {
        id: 5,
        nombre: "PERRO DEL FARAON",
        desc: "El perro del faraón o podenco faraónico es una raza de perro de tamaño mediano y pelo corto que destaca por su porte elegante y atlético. Se trata de un perro de caza originario de la isla de Malta. Aunque no es una de las razas más extendidas, este lebrel es un excelente perro de compañía, que destaca por su nobleza y fidelidad.",
        origen:"Malta",
        precio: 230000,
        img: 'src/https://t2.ea.ltmcdn.com/es/razas/4/8/8/perro-del-faraon_884_0_600.jpg',
        Stock: 2, 
    },
    {
        id: 6,
        nombre: "PERRO TAMASKAN",
        desc: "Si te gustan los perros con aspecto de lobo, el tamaskan te resultará una raza fascinante. Completamente diferente y con un temperamento único que lo convierte en un deportista nato, un perro de trabajo por excelencia y un maravilloso compañero de aventuras para tutores activos.",
        origen:"Finlandia",
        precio: 185000,
        img: 'src/https://t1.ea.ltmcdn.com/es/razas/3/8/8/tamaskan_883_0_600.jpg',
        Stock: 4,  
    },
    {
        id: 7,
        nombre: "PASTOR AMERICANO MINIATURA",
        desc: "El pastor americano miniatura, es un perro de pequeño tamaño que se originó a partir de perros pastores autralianos. Estos fueron creados a partir de perros europeos, principalmente españoles. Es un perro muy cariñoso, activo e inteligente, que adora pasar tiempo con sus cuidadores.",
        origen:"Estados Unidos",
        precio: 150000,
        img: 'src/https://t2.ea.ltmcdn.com/es/razas/7/7/8/pastor-americano-miniatura-o-pastor-australiano-miniatura_877_0_600.jpg',
        Stock: 1, 
    },
    {
        id: 8,
        nombre: "CLUMBER SPANIEL",
        desc: "El clumber spaniel es un perro que es para considerarse animales de compañía. Son unos perros corpulentos y pesados con una gran osamenta y un tamaño mediano. Tienen un carácter excepcional y su entrenamiento y educación son sencillos debido a su inteligencia y buena actitud.",
        origen:"Francia",
        precio: 210000,
        img: 'src/https://t1.ea.ltmcdn.com/es/razas/6/7/8/clumber-spaniel_876_0_600.jpg',
        Stock: 1,   
    },
     {
         id: 9,
         nombre: "EJEMPLO 1",
         desc: "Caninos",
         origen:"Francia",
         precio: 210000,
         img: 'src/https://t1.ea.ltmcdn.com/es/razas/5/8/8/black-mouth-cur_885_0_300_150.jpg',
         Stock: 1, 
     },
     {
         id: 10,
         nombre: "EJEMPLO 2",
         desc: "Caninos",
         origen:"Francia",
         precio: 210000,
         img: 'src/https://t1.ea.ltmcdn.com/es/razas/6/7/8/clumber-spaniel_876_0_600.jpg',
         Stock: 1,
     },
     {
         id: 11,
         nombre: "EJEMPLO 3",
         desc: "Caninos",
         origen:"Francia",
         precio: 210000,
         img: 'src/https://t1.ea.ltmcdn.com/es/razas/6/7/8/clumber-spaniel_876_0_600.jpg',
         Stock: 1,
     },
     {
         id: 12,
         nombre: "EJEMPLO 4",
         desc: "Caninos",
         origen:"Francia",
         precio: 210000,
         img: 'src/https://t1.ea.ltmcdn.com/es/razas/6/7/8/clumber-spaniel_876_0_600.jpg',
         Stock: 1,
     }
]

export default productos;